### PR TITLE
Transaction History Automation

### PR DESCRIPTION
**Pull request by Harshitha20-MCA**
Automate the testcases of transaction history by using java selenium and cucumber framework.

### CODE REVIEW

**Comment by Mangesh-Shirodkar** [comment]
Remove duplicate lines of code and Use common hooks

**Comment by Harshitha20-MCA** [comment]
I remove the duplicate lines of code and use common hooks to.

**Review by Mangesh-Shirodkar — COMMENTED** [review]
Use getText() function instead of getExpectedText() and remove getExpectedText()

**Comment by Mangesh-Shirodkar** [comment]
- Transaction history automation script is working fine

**Review by Mangesh-Shirodkar — APPROVED** [review]

**Pull request merged**
